### ISSUE TITLE
JSON error? User variable?

### ISSUE THREAD

**Issue by ghost** [ironman5366/search#1]
This is error i get when attempting to run it from the main function?

```
Traceback (most recent call last):
  File "search.py", line 98, in <module>
    main(query, user, appid)
  File "search.py", line 91, in main
    wlfram_search(query, user, appid)
  File "search.py", line 49, in wlfram_search
    google_search(user_query, user)
  File "search.py", line 72, in google_search
    results = json [ 'responseData' ] [ 'results' ]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Also the user variable doesn't have any reference it seems, and there are two modules that dont seem to be used (say, and wcycle)

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#Made by will beddow with the help of sulav khadka
import urllib2, urllib, json, re, wikipedia, wolframalpha
#import TTS_Talk
import json as m_json
import os
import __builtin__
# import say
# import wcycle
import requests

# def urlparse(url, searchterm, user):
# #Not working yet, will go into urls and search for results.
#   termsplit = searchterm.split(" ")
#   for word in termsplit:
#       r = requests.get(url)
#       rt = r.text
#       try:
#           #First split the text from the search term
#           rto = rt.split(word)
#           #Next search for the most recent html tag
#           rtp = rto[0].split('>')
#           #Next get everything ahead of that to the search term
#           firsttoterm = rtp[1]
#           #Next get the last html tag
#           rtn = rto[1].split('<')
#           #Next get everything behind that to the search term
#           lasttoterm = rtn[0]
#           finalresult = firsttoterm+word+lasttoterm
#           print(finalresult)
#       except IndexError:
#           pass

def wlfram_search(user_query, user, appid):
    try:
        client = wolframalpha.Client(appid)
        res = client.query(user_query)
        if next(res.results).text != 'None':
            #for i in res.pods:
                #print "\n"
                #print i.text
#           phrase = str(next(res.results).text)
#           TTS_Talk.tts_talk(phrase)
            print(next(res.results).text)
        else:
            google_search(user_query, user)
    except StopIteration:
        google_search(user_query, user)

def skwiki(titlequery, user):
    result = wikipedia.summary(titlequery, sentences=2)
    print(result)

def print_gsearch(results, user, searchterm):
    phrase = "I was unable to find an answer. Here are some links on the subject"
    #TTS_Talk.tts_talk(phrase)
        for result in results:
            title = result['title']
        url = result['url']
        pattern = re.compile('<.*?>')
        title = re.sub(pattern,'',title)
#       Uncomment the below line and comment the one under it to reenable the broken urlparse function
#       urlparse(url, searchterm, user)
        print(title+': '+url)

def google_search(user_query, user):
    query = user_query
        query = urllib.urlencode ( { 'q' : query } )
        response = urllib2.urlopen ( 'http://ajax.googleapis.com/ajax/services/search/web?v=1.0&' + query ).read()
        json = m_json.loads ( response )
        results = json [ 'responseData' ] [ 'results' ]
    wiki_bool = False
        for result in results:
            title = result['title']
        url = result['url']
        pattern = re.compile('<.*?>')
        title = re.sub(pattern,'',title)
        if "Wikipedia, the free encyclopedia" in title:
            titlelst = title.split('-')
            titlequery = titlelst[0].strip()
            skwiki(titlequery, user)
            wiki_bool = True
            break

    if wiki_bool == False:
        print_gsearch(results, user, user_query)


def main(query, user, appid):
    wlfram_search(query, user, appid)

#start main with an appid or uncomment the below line
appid = "Wolfram ID was removed because this may be public"
query = raw_input("What is your question?: ")
query = query.lower()
user = ""
main(query, user, appid)



```

**Comment by ironman5366** [comment]
Hi! Currently, that happens when there are no results found, just because I didn't catch that exception. It's a fairly easy fix, and the only reason I haven't gotten around to it is because the days of this module are numbered. Hopefully within the next few weeks I'll finish alot of the changes on my dev branch and pull it to master, and open up my servers. I've been working hard on setting up syntaxnet based parsing servers on digitalocean that will play a large roll in the new, and better framework.
Edit: sorry, I realized that this was out of context for this particular repo. This module is part of [W.I.L.L](https://github.com/ironman5366/W.I.L.L), and with a large update coming soon this will be improved. All the same, I'll fix that by adding a try/catch.

**Comment by ironman5366** [comment]
Fixed
